# Jekyll Configuration
#     - Configuration https://jekyllrb.com/docs/configuration/
#     - Default Configuration - https://jekyllrb.com/docs/configuration/default/
#     - Configuration Options - https://jekyllrb.com/docs/configuration/options/

# Site settings
title   : "EnjoyDev" # the name of your site, e.g. ACME Corp.
permalink: /:year/:title/

# Handling Reading
include:              #[".htaccess"]
  - _pages
exclude:              #  ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
  - run.cmd
  - README.md
  - CNAME
encoding            : "utf-8"

# Defaults
defaults:
  # default
  - scope:
      path: ""
    values:
      layout: "page"
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Sass/SCSS
sass:
  #sass_dir: # default "_sass"
  style: expanded # default : "compact". Development "expanded", Production "compressed"
